backend:
  image:
    repository: thanhthai298/yas-promotion
    tag: main

  nameOverride: promotion
  fullnameOverride: promotion
  databaseName: promotion
  ingress:
    enabled: true
    className: "nginx"
    annotations: {}
    host: api.yas.local.com
    path: /promotion
    pathType: Prefix
