backend:
  image:
    repository: thanhthai298/yas-promotion
    tag: main

  imagePullSecrets:
  - name: dockerhub-secret

  nameOverride: promotion
  fullnameOverride: promotion
  databaseName: promotion
  ingress:
    enabled: true
    className: ""
    annotations: {}
    host: api.yas.local.com
    path: /promotion
    pathType: Prefix
