# Application cho Dev
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thannthai/yas-gitops
    targetRevision: HEAD
    path: charts
    helm:
      ignoreMissingValueFiles: true   # không lỗi nếu values-dev.yaml chưa có
      valueFiles:
        - values.yaml        # config chung (base)
        - values-dev.yaml    # override tag cho dev namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
# Application cho Staging
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thannthai/yas-gitops
    targetRevision: HEAD
    path: charts
    helm:
      ignoreMissingValueFiles: true   # không lỗi nếu values-staging.yaml chưa có
      valueFiles:
        - values.yaml            # config chung (base)
        - values-staging.yaml    # override tag cho staging namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true