backend:
  image:
    repository: thanhthai298/yas-rating
    tag: main

  nameOverride: rating
  fullnameOverride: rating
  databaseName: rating
  ingress:
    enabled: true
    className: "nginx"
    annotations: {}
    host: api.yas.local.com
    path: /rating
    pathType: Prefix
