backend:
  image:
    repository: thanhthai298/yas-rating
    tag: main

  env:
    - name: MANAGEMENT_SERVER_PORT
      value: "8090"
    - name: SERVER_PORT
      value: "8080"

  nameOverride: rating
  fullnameOverride: rating
  databaseName: rating
  ingress:
    enabled: false
