backend:
  image:
    repository: thanhthai298/yas-webhook
    tag: main

  env:
    - name: MANAGEMENT_SERVER_PORT
      value: "8090"
    - name: SERVER_PORT
      value: "8080"

  nameOverride: webhook
  fullnameOverride: webhook
  databaseName: webhook
