backend:
  image:
    repository: thanhthai298/yas-webhook
    tag: main

  ingress:
    enabled: true
    className: "nginx"
    annotations: {}
    host: api.yas.local.com
    path: /webhook
    pathType: Prefix

  nameOverride: webhook
  fullnameOverride: webhook
  databaseName: webhook
