backend:
  image:
    repository: thanhthai298/yas-webhook
    tag: main

  imagePullSecrets:
  - name: dockerhub-secret

  ingress:
    enabled: true
    className: ""
    annotations: {}
    host: api.yas.local.com
    path: /webhook
    pathType: Prefix

  nameOverride: webhook
  fullnameOverride: webhook
  databaseName: webhook
