backend:
  image:
    repository: thanhthai298/yas-search
    tag: main

  nameOverride: search
  fullnameOverride: search
  databaseName: search
  ingress:
    enabled: true
    className: "nginx"
    annotations: {}
    host: api.yas.local.com
    path: /search
    pathType: Prefix
  extraEnvFroms:
    - secretRef:
        name: yas-elasticsearch-credentials-secret
  extraVolumes:
    - name: search-application
      configMap:
        name: search-application-configmap
  extraVolumeMounts:
    - name: search-application
      mountPath: /opt/yas/search
  extraApplicationConfigPaths:
    - /opt/yas/search/search-application.yaml
