backend:
  image:
    repository: thanhthai298/yas-search
    tag: main

  imagePullSecrets:
  - name: dockerhub-secret

  elasticsearch:
    url: https://elasticsearch-es-http.elasticsearch.svc.cluster.local:9200
    username: elastic
    password: ZiG0P5GLgJgvtatjsazWAKY3

  nameOverride: search
  fullnameOverride: search
  databaseName: search
  ingress:
    enabled: true
    className: ""
    annotations: {}
    host: api.yas.local.com
    path: /search
    pathType: Prefix
  extraEnvFroms:
    - secretRef:
        name: yas-elasticsearch-credentials-secret
  extraVolumes:
    - name: search-application
      configMap:
        name: search-application-configmap
  extraVolumeMounts:
    - name: search-application
      mountPath: /opt/yas/search
  extraApplicationConfigPaths:
    - /opt/yas/search/search-application.yaml
