backend:
  image:
    repository: thanhthai298/yas-location
    tag: main


  nameOverride: location
  fullnameOverride: location
  databaseName: location
  ingress:
    enabled: true
    className: "nginx"
    annotations: {}
    host: api.yas.local.com
    path: /location
    pathType: Prefix
