backend:
  image:
    repository: thanhthai298/yas-location
    tag: main

  imagePullSecrets:
    - name: dockerhub-secret

  nameOverride: location
  fullnameOverride: location
  databaseName: location
  ingress:
    enabled: true
    className: ""
    annotations: {}
    host: api.yas.local.com
    path: /location
    pathType: Prefix
