backend:
  image:
    repository: thanhthai298/yas-location
    tag: main

  env:
    - name: MANAGEMENT_SERVER_PORT
      value: "8090"
    - name: SERVER_PORT
      value: "8080"

  nameOverride: location
  fullnameOverride: location
  databaseName: location
  ingress:
    enabled: false
