backend:
  image:
    repository: thanhthai298/yas-sampledata
    tag: main

  nameOverride: sampledata
  fullnameOverride: sampledata
  databaseName: sampledata
  ingress:
    enabled: true
    className: ""
    annotations: {}
    host: api.yas.local.com
    path: /sampledata
    pathType: Prefix
  extraVolumes:
    - name: sampledata-application
      configMap:
        name: sampledata-application-configmap
  extraVolumeMounts:
    - name: sampledata-application
      mountPath: /opt/yas/sampledata
  extraApplicationConfigPaths:
    - /opt/yas/sampledata/sampledata-application.yaml
