ui:
  image:
    repository: thanhthai298/yas-storefront
    tag: latest

  imagePullSecrets:
  - name: dockerhub-secret

  nameOverride: storefront-ui
  fullnameOverride: storefront-ui
  extraEnvs:
    - name: API_BASE_PATH
      value: http://storefront.yas.local.com/api
  ingress:
    enabled: false