backend:
  image:
    repository: thanhthai298/yas-backoffice-bff
    tag: main

  imagePullSecrets:
  - name: dockerhub-secret

  nameOverride: backoffice-bff
  fullnameOverride: backoffice-bff

  httpPort: 80

  deployment:
    annotations:
      configmap.reloader.stakater.com/reload: "yas-gateway-routes-config-configmap,backoffice-bff-extra-configmap"
  ingress:
    enabled: true
    host: backoffice.yas.local.com
    path: /
  extraEnvs:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: UI_HOST
      value: http://backoffice-ui:3000
    - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
      value: http://identity.yas.local.com/realms/Yas
  extraEnvFroms:
    - secretRef:
        name: yas-keycloak-credentials-secret
    - secretRef:
        name: yas-redis-credentials-secret
  extraVolumes:
    - name: yas-gateway-routes-config
      configMap:
        name: yas-gateway-routes-config-configmap
    - name: backoffice-bff-extra-config
      configMap:
        name: backoffice-bff-extra-configmap
  extraVolumeMounts:
    - name: yas-gateway-routes-config
      mountPath: /opt/yas/gateway-routes-config
    - name: backoffice-bff-extra-config
      mountPath: /opt/yas/extra-config
  extraApplicationConfigPaths:
    - file:/opt/yas/gateway-routes-config/gateway-routes-config.yaml
    - file:/opt/yas/extra-config/backoffice-bff-extra-config.yaml