backend:
  image:
    repository: thanhthai298/yas-media
    tag: main

  env:
    - name: MANAGEMENT_SERVER_PORT
      value: "8090"
    - name: SERVER_PORT
      value: "8080"

  nameOverride: media
  fullnameOverride: media
  databaseName: media
  ingress:
    enabled: false
  extraVolumes:
    - name: media-application
      configMap:
        name: media-application-configmap
  extraVolumeMounts:
    - name: media-application
      mountPath: /opt/yas/media
  extraApplicationConfigPaths:
    - /opt/yas/media/media-application.yaml

