backend:
  image:
    repository: thanhthai298/yas-payment-paypal
    tag: main

  env:
    - name: MANAGEMENT_SERVER_PORT
      value: "8090"
    - name: SERVER_PORT
      value: "8080"

  nameOverride: payment-paypal
  fullnameOverride: payment-paypal
  databaseName: payment-paypal
  ingress:
    enabled: false
  extraVolumes:
    - name: payment-paypal-application-config
      configMap:
        name: payment-paypal-application-configmap
  extraVolumeMounts:
    - name: payment-paypal-application-config
      mountPath: /opt/yas/payment-paypal
  extraApplicationConfigPaths:
    - /opt/yas/payment-paypal/payment-paypal-application.yaml