backend:
  image:
    repository: thanhthai298/yas-inventory
    tag: main

  imagePullSecrets:
  - name: dockerhub-secret

  nameOverride: inventory
  fullnameOverride: inventory
  databaseName: inventory
  ingress:
    enabled: true
    className: ""
    annotations: {}
    host: api.yas.local.com
    path: /inventory
    pathType: Prefix
