backend:
  image:
    repository: thanhthai298/yas-tax
    tag: main

  nameOverride: tax
  fullnameOverride: tax
  databaseName: tax
  ingress:
    enabled: true
    className: "nginx"
    annotations: {}
    host: api.yas.local.com
    path: /tax
    pathType: Prefix
