ui:
  image:
    repository: thanhthai298/yas-backoffice
    tag: latest

  imagePullSecrets:
  - name: dockerhub-secret

  nameOverride: backoffice-ui
  fullnameOverride: backoffice-ui
  extraEnvs:
    - name: API_BASE_PATH
      value: http://backoffice.yas.local.com/api
  ingress:
    enabled: false